name: Update NRD Blocklist

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # 👈 allows the action to push commits

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # built-in token with write access

      - name: Fetch blocklist
        run: |
          mkdir -p lists
          curl -sSL "https://raw.githubusercontent.com/xRuffKez/NRD/refs/heads/main/lists/14-day-mini/domains-only/nrd-14day-mini.txt" \
            -o lists/nrd-14day-mini.txt

      - name: Remove .ru and .cn
        run: |
          grep -viE "\.ru$|\.cn$" lists/nrd-14day-mini.txt > lists/blocklist-clean.txt
          mv lists/blocklist-clean.txt lists/nrd-14day-mini.txt

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add lists/nrd-14day-mini.txt
            git commit -m "Update NRD blocklist (remove .ru and .cn)"
            git push
          else
            echo "No changes to commit."
          fi
